# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inventory.proto',
  package='inventory',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0finventory.proto\x12\tinventory\"2\n\x11\x43reateBookRequest\x12\x1d\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.inventory.Book\"\"\n\x12\x43reateBookResponse\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"f\n\x0fGetBookResponse\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"\xa9\x01\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12(\n\x05genre\x18\x04 \x01(\x0e\x32\x19.inventory.Book.GenreType\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"1\n\tGenreType\x12\x0c\n\x08THRILLER\x10\x00\x12\n\n\x06\x43OMEDY\x10\x01\x12\n\n\x06TRAGIC\x10\x02\"\xaf\x01\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\x05\x12\x1f\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x0f.inventory.BookH\x00\x12\x33\n\x06status\x18\x03 \x01(\x0e\x32#.inventory.InventoryItem.StatusType\"&\n\nStatusType\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x06\n\x04item2\x9f\x01\n\x10InventoryService\x12I\n\nCreateBook\x12\x1c.inventory.CreateBookRequest\x1a\x1d.inventory.CreateBookResponse\x12@\n\x07GetBook\x12\x19.inventory.GetBookRequest\x1a\x1a.inventory.GetBookResponseb\x06proto3'
)



_BOOK_GENRETYPE = _descriptor.EnumDescriptor(
  name='GenreType',
  full_name='inventory.Book.GenreType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='THRILLER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMEDY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRAGIC', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=375,
  serialized_end=424,
)
_sym_db.RegisterEnumDescriptor(_BOOK_GENRETYPE)

_INVENTORYITEM_STATUSTYPE = _descriptor.EnumDescriptor(
  name='StatusType',
  full_name='inventory.InventoryItem.StatusType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AVAILABLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TAKEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=556,
  serialized_end=594,
)
_sym_db.RegisterEnumDescriptor(_INVENTORYITEM_STATUSTYPE)


_CREATEBOOKREQUEST = _descriptor.Descriptor(
  name='CreateBookRequest',
  full_name='inventory.CreateBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='book', full_name='inventory.CreateBookRequest.book', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=80,
)


_CREATEBOOKRESPONSE = _descriptor.Descriptor(
  name='CreateBookResponse',
  full_name='inventory.CreateBookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='inventory.CreateBookResponse.isbn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=116,
)


_GETBOOKREQUEST = _descriptor.Descriptor(
  name='GetBookRequest',
  full_name='inventory.GetBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='inventory.GetBookRequest.isbn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=148,
)


_GETBOOKRESPONSE = _descriptor.Descriptor(
  name='GetBookResponse',
  full_name='inventory.GetBookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='inventory.GetBookResponse.isbn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='inventory.GetBookResponse.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='inventory.GetBookResponse.author', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genre', full_name='inventory.GetBookResponse.genre', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publishing_year', full_name='inventory.GetBookResponse.publishing_year', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=252,
)


_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='inventory.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='inventory.Book.isbn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='inventory.Book.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='inventory.Book.author', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genre', full_name='inventory.Book.genre', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='publishing_year', full_name='inventory.Book.publishing_year', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BOOK_GENRETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=424,
)


_INVENTORYITEM = _descriptor.Descriptor(
  name='InventoryItem',
  full_name='inventory.InventoryItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inventory_number', full_name='inventory.InventoryItem.inventory_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='book', full_name='inventory.InventoryItem.book', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='inventory.InventoryItem.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INVENTORYITEM_STATUSTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='item', full_name='inventory.InventoryItem.item',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=427,
  serialized_end=602,
)

_CREATEBOOKREQUEST.fields_by_name['book'].message_type = _BOOK
_BOOK.fields_by_name['genre'].enum_type = _BOOK_GENRETYPE
_BOOK_GENRETYPE.containing_type = _BOOK
_INVENTORYITEM.fields_by_name['book'].message_type = _BOOK
_INVENTORYITEM.fields_by_name['status'].enum_type = _INVENTORYITEM_STATUSTYPE
_INVENTORYITEM_STATUSTYPE.containing_type = _INVENTORYITEM
_INVENTORYITEM.oneofs_by_name['item'].fields.append(
  _INVENTORYITEM.fields_by_name['book'])
_INVENTORYITEM.fields_by_name['book'].containing_oneof = _INVENTORYITEM.oneofs_by_name['item']
DESCRIPTOR.message_types_by_name['CreateBookRequest'] = _CREATEBOOKREQUEST
DESCRIPTOR.message_types_by_name['CreateBookResponse'] = _CREATEBOOKRESPONSE
DESCRIPTOR.message_types_by_name['GetBookRequest'] = _GETBOOKREQUEST
DESCRIPTOR.message_types_by_name['GetBookResponse'] = _GETBOOKRESPONSE
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['InventoryItem'] = _INVENTORYITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateBookRequest = _reflection.GeneratedProtocolMessageType('CreateBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEBOOKREQUEST,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:inventory.CreateBookRequest)
  })
_sym_db.RegisterMessage(CreateBookRequest)

CreateBookResponse = _reflection.GeneratedProtocolMessageType('CreateBookResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEBOOKRESPONSE,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:inventory.CreateBookResponse)
  })
_sym_db.RegisterMessage(CreateBookResponse)

GetBookRequest = _reflection.GeneratedProtocolMessageType('GetBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKREQUEST,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:inventory.GetBookRequest)
  })
_sym_db.RegisterMessage(GetBookRequest)

GetBookResponse = _reflection.GeneratedProtocolMessageType('GetBookResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKRESPONSE,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:inventory.GetBookResponse)
  })
_sym_db.RegisterMessage(GetBookResponse)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:inventory.Book)
  })
_sym_db.RegisterMessage(Book)

InventoryItem = _reflection.GeneratedProtocolMessageType('InventoryItem', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORYITEM,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:inventory.InventoryItem)
  })
_sym_db.RegisterMessage(InventoryItem)



_INVENTORYSERVICE = _descriptor.ServiceDescriptor(
  name='InventoryService',
  full_name='inventory.InventoryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=605,
  serialized_end=764,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateBook',
    full_name='inventory.InventoryService.CreateBook',
    index=0,
    containing_service=None,
    input_type=_CREATEBOOKREQUEST,
    output_type=_CREATEBOOKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBook',
    full_name='inventory.InventoryService.GetBook',
    index=1,
    containing_service=None,
    input_type=_GETBOOKREQUEST,
    output_type=_GETBOOKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVENTORYSERVICE)

DESCRIPTOR.services_by_name['InventoryService'] = _INVENTORYSERVICE

# @@protoc_insertion_point(module_scope)
